### ISSUE TITLE
Add a -y flag to auto accept flag

### ISSUE THREAD

**Issue by brisc** [ruimarinho/shelly-updater#1]
If you have a lot of devices, you need to press Y for each device, which takes tens of minutes.
Add a -y flag to auto-accept all upgrades

![image](https://user-images.githubusercontent.com/209979/110201561-5dc9b500-7e6c-11eb-8bd7-ea5c40ef652d.png)

**Comment by ruimarinho** [comment]
Implemented in [v1.1.0](https://github.com/ruimarinho/shelly-updater/tree/v1.1.0) using `-f` (force mode).
