### ISSUE TITLE
Home Assistant Community Addon

### ISSUE THREAD

**Issue by chriscn** [ruimarinho/shelly-updater#3]
I'm not sure if this is out of scope of the project or not but this could be a really great implementation of the project being a HASS addon. I believe they use docker for the backend deployment and management of services. 

I for one will plan to have my Shelly's on a separate VLAN but still accessible to my Home Assistant and so this would be a great option.

**Comment by ruimarinho** [comment]
Hi @chriscn. I think this would be a great addition to the native Shelly add-on for HASS, with or without using this project's code. I would certainly welcome that, but right now it's out of scope for this project. Thanks for the suggestion though!
