### ISSUE TITLE
Can´t authenticate

### ISSUE THREAD

**Issue by yahwehPT** [ruimarinho/shelly-updater#4]
Using ubuntu, created file ~/.netrc and inserted:
machine 192.168.3.200
login myuser
password mypassword 
and get:
time="2021-03-11T17:54:36Z" level=error msg="Unable to fetch settings from shellyplug-s-aaa.local. (192.168.3.200:80) due to incorrect or missing username/password"
any help?

also feature request: please allow for a general user and password, I use the same user and password for all my shelly.

Thank you
Obrigado

**Comment by ruimarinho** [comment]
Hi @yahwehPT,

Can you run in verbose mode (`--verbose`) and paste the output here?

**Comment by yahwehPT** [comment]
sorry for late reply. Verbose mode doesn't print anything that normal mode doesn't. I'm using docker and version `mota 2.0.0 (ba5a258d503e1914575cbad7d43206502bec8474 2021-03-10T00:35:13Z)`
command for docker was:  `sudo docker run --rm --net=host ruimarinho/mota --verbose`

in the end I get: ` level=fatal msg="Get \"https://api.shelly.cloud/files/firmware\": x509: certificate signed by unknown authority"
`

**Comment by ruimarinho** [comment]
You need to mount your netrc file into the docker volume for it to work (use `-v <hostFile>:<containerFile>`).

**Comment by ruimarinho** [comment]
I've just pushed a fix for the TLS certificate message you're getting.
