### ISSUE TITLE
error on docker

### ISSUE THREAD

**Issue by yahwehPT** [ruimarinho/shelly-updater#5]
` Would you like to upgrade Shelly Plug S (192.168.3.200) from 20210312-134501/v1.10.0-rc5-g1c546b5 to 20210115-103659/v1.9.4@e2732e05? (y/N)                                                time="2021-03-17T23:09:03Z" level=fatal msg=EOF`

didn't wait for y/n input

edit: I've mounted .cache/com.github.ruimarinho.mota/ to container but same error

**Comment by ruimarinho** [comment]
Hi,

Are you using interactive mode with `-it`?

If you're new to docker, you could try running the linux version directly as it works quite well too!
