### ISSUE TITLE
Argument to skip download firmware from internet.

### ISSUE THREAD

**Issue by pixiandreas** [ruimarinho/shelly-updater#6]
Can now add an argument so you skip the part that downloads the file from the internet.
Of course i must run this once with internet.

Have some Shelly that are completely blocked, so would like to update with an already downloaded file on my update computer.

**Comment by ruimarinho** [comment]
Hi! The objective is to run this on a device with internet access while keeping Shelly's away from it. Once the firmware ir downloaded once from the internet, it is cached on your local computer.

I hope this helps!

**Comment by pixiandreas** [comment]
Hi again.
I just try it now.
First connected to wifi with internet.
`
time="2021-04-08T21:47:25+02:00" level=debug msg="Downloaded firmware SHDM-2.zip to /home/andreas/.cache/com.github.ruimarinho.mota/SHDM-2-20210323-110201-v1.10.1-gf276b51.zip\n"
time="2021-04-08T21:47:25+02:00" level=debug msg="Adding HTTP handler for /SHDM-2"
? Would you like to upgrade Shelly Dimmer 2 (192.168.50.60) from 20201228-093141/v1.9.3@ad2bb4e3 to 
20210323-110201/v1.10.1-gf276b51? Would you like to upgrade Shelly Dimmer 2 (192.168.50.60) from 
20201228-093141/v1.9.3@ad2bb4e3 to 20210323-110201/v1.10.1-gf276b51? Yes
time="2021-04-08T21:48:08+02:00" level=debug msg="Making OTA request to http://:@192.168.50.60:80/ota?url=http://192.168.7.182:0/SHDM-2"
time="2021-04-08T21:48:18+02:00" level=info msg="Done!"
`
Then i connect to the iot network
and run the command again.
`
andreas@siv:~/Downloads$ ./mota  --host 192.168.50.60
INFO[0000] Listening for HTTP server on port 0          
INFO[0000] Preparing to update devices with hosts [192.168.50.60] 
INFO[0000] Found device 192.168.50.60:80 (192.168.50.60) 
INFO[0000] Fetching settings from 192.168.50.60:80 (192.168.50.60:80) 
FATA[0010] Get "https://api.shelly.cloud/files/firmware": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
`

I can ping the device 192.168.50.60
and the internal shelly web server works as well.

**Comment by ruimarinho** [comment]
Hi @pixiandreas do you have connectivity between your main LAN and the IoT LAN? The way mota is designed is for that specific use case, because most likely you have some sort of hub on a LAN with connectivity, presumably the same you are on typically with your laptop.

So you'd keep your laptop to the wifi with internet and then make the IoT device update through that same device. Shelly connects to your laptop instead of the internet. Does that make sense?

**Comment by pixiandreas** [comment]
You're right, there was a miss configuration in my network, case closed :-)
